// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetSocket(arg1) {
  return window['go']['main']['App']['GetSocket'](arg1);
}

export function SetSocket(arg1) {
  return window['go']['main']['App']['SetSocket'](arg1);
}
